global:
  message: Welcome to order service prod environment!!
server:
  port: 8085
message: Hello from Prod!
spring:
  datasource:
     url: jdbc:mysql://localhost:3306/order_prod
     username: root
     password: password123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
